### ISSUE TITLE
Pairing failed with status 0x11 (Invalid Index)

### ISSUE THREAD

**Issue by Hugo-prod** [TarlogicSecurity/BlueSpy#12]
Hello,

my setup:
- VMware -> Kali
- USB Bluetooth dongle - https://fr.ugreen.com/products/ugreen-dongle-bluetooth-5-0-cle-usb-bluetooth
- My 2nd dongle: https://www.amazon.fr/dp/B0CBK7WRPT?psc=1&ref=ppx_yo2ov_dt_b_product_details

I can discover it with bluetoothctl and connect to it with blueman-applet on my kali   
But with btmgmt i get `0x11 (Invalid Index)` with any peripheral

Any idea ?

```bash
┌──(kali㉿kali)-[~/Documents/BlueSpy]
└─$ sudo python BlueSpy.py -a 11:75:58:13:F1:DC
░█▀▄░█░░░█░█░█▀▀░█▀▀░█▀█░█░█░
░█▀▄░█░░░█░█░█▀▀░▀▀█░█▀▀░░█░░
░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░░░░▀░░
░▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀░
Bluetooth audio recording tool by Tarlogic
[I] Avoiding authentication with 11:75:58:13:F1:DC...
[I] Generating shared key...
Traceback (most recent call last):
  File "/home/kali/Documents/BlueSpy/BlueSpy.py", line 94, in <module>
    main()
  File "/home/kali/Documents/BlueSpy/BlueSpy.py", line 67, in main
    paired = pair(target, verbose=args.verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documents/BlueSpy/core.py", line 90, in pair
    raise e
  File "/home/kali/Documents/BlueSpy/core.py", line 79, in pair
    run_and_check(
  File "/home/kali/Documents/BlueSpy/system.py", line 35, in run_and_check
    raise CommandValidationException(cmdline, out)
system.CommandValidationException: ('Error while executing command "sudo btmgmt pair -c 3 -t 0 11:75:58:13:f1:dc"', 'Pairing with 11:75:58:13:F1:DC (BR/EDR)\n\x1b[0;91mPairing failed with status 0x11 (Invalid Index)\n\x1b[0m')
```

```bash                                                                                                                  
┌──(kali㉿kali)-[~/Documents/BlueSpy]
└─$ sudo btmgmt pair -c 3 -t 0 11:75:58:13:f1:dc
Pairing with 11:75:58:13:F1:DC (BR/EDR)
Pairing failed with status 0x11 (Invalid Index)
```

**Comment by jesusgomezmoreno** [comment]
Can you connect and pair to the device using bluetoothctl? Do you have any wireshark capture of the connection using blueman-applet?
