### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hisbalah** [TarlogicSecurity/BlueSpy#17]

**Comment by hisbalah** [comment]
[](url)[
![Uploading PXL_20240720_090815578.jpg…]()
](url)

**Comment by hisbalah** [comment]
Bluetooth audio recording tool by Tarlogic

[I] Avoiding authentication with 94:45:60:5A:F3:B0

[I] Generating shared key...

[!] Key generated

[I] The device is vulnerable! [I] Establishing connection...

Traceback (most recent call last):

File "/home/kali/BlueSpy/BlueSpy.py", line 94, in <module>

main()

File "/home/kali/BlueSpy/BlueSpy.py", line 78, in main connect(target, verbose-args.verbose)

File "/home/kali/BlueSpy/core.py", line 97, in connect

run_and_check(

File "/home/kali/BlueSpy/system.py", line 35, in run_and_check raise CommandValidationException(cmdline, out)

system.CommandValidationException: ('Error while executing command "bluetoothctl connect 94:45:60:5a:f3:b0"', 'Attemp ting to connect to 94:45:60:5a:f3:b0\nhci0 device_flags_changed: 94:45:60:5A:F3:80 (BR/EDR)\n urr: 0x00000000\nFailed to connect: org.bluez.Error.Failed br-connection-profile-unavailable\n


What with this?
